In [1]:
#Import The Libraries
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
%matplotlib inline

In [4]:
#Importing the Dataset
df = pd.read_csv('Churn_Modelling.csv')

In [7]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [59]:
X = df.iloc[:,3:13].values
y = df['Exited'].values

In [61]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [62]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [63]:
#Encoding Categorical Data
import sklearn

In [64]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [65]:
label_encoder1 = LabelEncoder()

In [67]:
X[:,1] = label_encoder1.fit_transform(X[:,1])

In [68]:
label_encoder2 = LabelEncoder()

In [70]:
X[:, 2] = label_encoder2.fit_transform(X[:, 2])

In [71]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [72]:
onehotencoder = OneHotEncoder(categorical_features=[1]) 

In [73]:
X = onehotencoder.fit_transform(X).toarray()

C:\Users\akash\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\akash\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [76]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [77]:
X = X[:, 1:]

In [78]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [80]:
#Spliting the Dataset into Ttaining and testing datasets
from sklearn.model_selection import train_test_split

In [87]:
 X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.2, random_state=0)

In [88]:
X_train

array([[0.0000000e+00, 1.0000000e+00, 6.6700000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.6383064e+05],
       [1.0000000e+00, 0.0000000e+00, 4.2700000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 5.7098000e+04],
       [0.0000000e+00, 0.0000000e+00, 5.3500000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.8563076e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.3800000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.8142987e+05],
       [0.0000000e+00, 1.0000000e+00, 5.9000000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.4875016e+05],
       [1.0000000e+00, 0.0000000e+00, 6.2300000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1885526e+05]])

In [89]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

In [90]:
sc = StandardScaler()

In [93]:
X_train = sc.fit_transform(X_train)
X_test =sc.transform(X_test)

In [94]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [98]:
#Making ANN
#Importing Karas libraries and packages
import keras 
from keras.models import Sequential
from keras.layers import Dense

In [100]:
#Initialising the ANN
classifier = Sequential()

W0824 12:52:39.124626  4356 deprecation_wrapper.py:119] From C:\Users\akash\Anaconda3\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [101]:
#Adding the input layer and the first hidden layer
#Rectifier Activation Function For Hidden Layers
#Sigmoid Function For Output Layers
classifier.add(Dense(output_dim = 6,init = 'uniform', activation = 'relu', input_dim = 11))

C:\Users\akash\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
W0824 13:18:56.674442  4356 deprecation_wrapper.py:119] From C:\Users\akash\Anaconda3\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0824 13:18:57.088938  4356 deprecation_wrapper.py:119] From C:\Users\akash\Anaconda3\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [102]:
#adding the second hidden layer
classifier.add(Dense(output_dim = 6,init = 'uniform', activation = 'relu'))


C:\Users\akash\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [103]:
#adding the output layer
classifier.add(Dense(output_dim = 1,init = 'uniform', activation = 'sigmoid'))

C:\Users\akash\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [104]:
#Compiling the ANN
classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

W0824 13:33:05.574474  4356 deprecation_wrapper.py:119] From C:\Users\akash\Anaconda3\envs\tensorflow\lib\site-packages\keras\optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0824 13:33:05.768955  4356 deprecation_wrapper.py:119] From C:\Users\akash\Anaconda3\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py:3657: The name tf.log is deprecated. Please use tf.math.log instead.

W0824 13:33:05.782949  4356 deprecation.py:323] From C:\Users\akash\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [105]:
# Fitting the ANN to the Training datasets
classifier.fit(X_train, y_train, batch_size= 10, epochs = 100)

W0824 13:37:25.432297  4356 deprecation_wrapper.py:119] From C:\Users\akash\Anaconda3\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
8000/8000 [==============================] - 3s 377us/step - loss: 0.4819 - acc: 0.7954
Epoch 2/100
8000/8000 [==============================] - 2s 202us/step - loss: 0.4290 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 254us/step - loss: 0.4239 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 222us/step - loss: 0.4193 - acc: 0.8176
Epoch 5/100
8000/8000 [==============================] - 2s 226us/step - loss: 0.4166 - acc: 0.8247
Epoch 6/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.4151 - acc: 0.8292
Epoch 7/100
8000/8000 [==============================] - 2s 197us/step - loss: 0.4136 - acc: 0.8324
Epoch 8/100
8000/8000 [==============================] - 2s 221us/step - loss: 0.4121 - acc: 0.8327
Epoch 9/100
8000/8000 [==============================] - 2s 219us/step - loss: 0.4109 - acc: 0.8327
Epoch 10/100
8000/8000 [==============================] - 2s 251us/step - loss: 0.4101 - acc: 0.8337

8000/8000 [==============================] - 1s 171us/step - loss: 0.4003 - acc: 0.8352 0s - loss: 0.4039 
Epoch 83/100
8000/8000 [==============================] - 1s 169us/step - loss: 0.3997 - acc: 0.8344
Epoch 84/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3995 - acc: 0.8346
Epoch 85/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3996 - acc: 0.8357
Epoch 86/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3999 - acc: 0.8345
Epoch 87/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3997 - acc: 0.8351
Epoch 88/100
8000/8000 [==============================] - 2s 196us/step - loss: 0.3997 - acc: 0.8360
Epoch 89/100
8000/8000 [==============================] - 2s 196us/step - loss: 0.3996 - acc: 0.8347
Epoch 90/100
8000/8000 [==============================] - 2s 193us/step - loss: 0.3995 - acc: 0.8344
Epoch 91/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.399

In [106]:
#making the prediction
y_pred = classifier.predict(X_test)

In [109]:
y_pred = (y_pred>0.6)

In [110]:
from sklearn.metrics import classification_report, confusion_matrix

In [112]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89      1595
           1       0.00      0.00      0.00       405

    accuracy                           0.80      2000
   macro avg       0.40      0.50      0.44      2000
weighted avg       0.64      0.80      0.71      2000

[[1595    0]
 [ 405    0]]


C:\Users\akash\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [113]:
acc = 1595/2000

In [114]:
acc

0.7975